version: '3.8'

services:
  nginx:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: usr-wordpress
      WORDPRESS_DB_PASSWORD: pwd-wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: wordpress
      MYSQL_USER: usr-wordpress
      MYSQL_PASSWORD: pwd-wordpress
    volumes:
      - db_data:/var/lib/mysql

  locust:
    image: grubykarol/locust
    container_name: locust
    environment:
      ATTACKED_HOST: http://nginx  # Define o host do teste como o serviço do nginx
      LOCUST_FILE: /locust/locustfile.py # Script locust para teste
      LOCUST_OPTS: "--users 10 --spawn-rate 1" # Parâmetros atualizados para usuários e taxa de spawn
    volumes:
      - ./locust-scripts:/locust # Volume para os scripts do Locust
    ports:
      - "8089:8089" # Porta de interface do Locust
    depends_on:
      - nginx # Locust espera o nginx iniciar

volumes:
  db_data:
